### ISSUE TITLE
README.md has wrong link to MSDK User Guide

### ISSUE THREAD

**Issue by LukeRJamieson** [analogdevicesinc/VSCode-Maxim#22]
Actual MSDK User Guide link: https://analogdevicesinc.github.io/msdk//USERGUIDE/

**Comment by Jake-Carter** [comment]
Thanks @LukeRJamieson, the links are fixed in the main branch.  Just need to push a v1.7.1 release so that the installer will link to an updated copy

**Comment by Jake-Carter** [comment]
Resolved as of the [Oct 2024](https://github.com/analogdevicesinc/msdk/releases/tag/v2024_10) MSDK release and the [v1.7.1](https://github.com/analogdevicesinc/VSCode-Maxim/releases/tag/v1.7.1) release tag.

FYI this took so long because publication of the MSDK release was de-prioritized in favor of [CodeFusion Studio](https://developer.analog.com/solutions/codefusionstudio) (CFS) for the past year.

This project has been merged into CFS and will be archived
